# Generated by Django 3.1.4 on 2021-01-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='action_text',
            field=models.CharField(default='shop now', max_length=20, verbose_name='action text'),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='action_url',
            field=models.URLField(default='http://127.0.0.1:8000', verbose_name='action url'),
        ),
    ]
